# This file takes the resulting RDS fails generated by `Real_data.R` and extracts
# the main results (AUC and QS values as well as differences between methods (oversampling, SMOTE) and control).
# Nothing needs to be set manually.

library(tidyverse) # General R work

source("functions.R")

data_id_vec <- c(271, 326, 332)

type_vec <- c("MLE", "LASSO")

for (data_id in data_id_vec) {
  diff_list <- list()
  for (i in seq_along(type_vec)) {
    res <- readRDS(file = paste0("data_", data_id, "_", type_vec[i], "_res.RDS"))
    
    diff_list[[i]] <- res$results$values %>%
      mutate(AUC_diff_up    = `up~AUC`    - `control~AUC`,
             AUC_diff_smote = `smote~AUC` - `control~AUC`,
             QS_diff_up     = `up~QS`     - `control~QS`,
             QS_diff_smote  = `smote~QS`  - `control~QS`) %>% 
      pivot_longer(cols = c(contains("diff"), contains("~"))) %>% 
      mutate(type = type_vec[i])
    
  }
  diff <- rbind(diff_list[[1]], diff_list[[2]])
  saveRDS(diff, file = paste0("data_", data_id, "_diff.RDS"))
}